# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repos < Formula
  desc "Cross-platform CLI for managing multiple related Git repositories as a unified workspace"
  homepage "https://github.com/MiguelRodo/repos"
  version "2.7.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/MiguelRodo/repos/releases/download/v2.7.1/repos_2.7.1_darwin_amd64.tar.gz"
      sha256 "14aa862deba869201a1b86438d033ff7ccd7d7d521f140c7e4bbc750eff40521"

      def install
        bin.install "repos"
      end
    end
    on_arm do
      url "https://github.com/MiguelRodo/repos/releases/download/v2.7.1/repos_2.7.1_darwin_arm64.tar.gz"
      sha256 "ba48df64472219b78a21cfd706a79b65210684804e0166bddaf7a2b59c5f3114"

      def install
        bin.install "repos"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/repos/releases/download/v2.7.1/repos_2.7.1_linux_amd64.tar.gz"
        sha256 "06856b8fe3bec8564b3bc7a14c2342ea252eb5a429d6c8c5cd231bb748811a30"

        def install
          bin.install "repos"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/repos/releases/download/v2.7.1/repos_2.7.1_linux_arm64.tar.gz"
        sha256 "b197cdb8398bf6cbe8e3a2b493610b8a0caa937eb8182f3b8e0441787f0343ed"

        def install
          bin.install "repos"
        end
      end
    end
  end
end
