# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repos < Formula
  desc "Cross-platform CLI for managing multiple related Git repositories as a unified workspace"
  homepage "https://github.com/MiguelRodo/repos"
  version "2.7.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/MiguelRodo/repos/releases/download/v2.7.0/repos_2.7.0_darwin_amd64.tar.gz"
      sha256 "2774607b7a90fe015920a645b2ebc192705e89f45c1233ab7c6120c33db2f46c"

      def install
        bin.install "repos"
      end
    end
    on_arm do
      url "https://github.com/MiguelRodo/repos/releases/download/v2.7.0/repos_2.7.0_darwin_arm64.tar.gz"
      sha256 "a750293d832d6bc2ef09d5a3968cab06cb49c86599b5ae64f702470a71220ce9"

      def install
        bin.install "repos"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/repos/releases/download/v2.7.0/repos_2.7.0_linux_amd64.tar.gz"
        sha256 "c34d02311af7fbd44958706609a1c20c6eba581059612473a0130b167d66b417"

        def install
          bin.install "repos"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/repos/releases/download/v2.7.0/repos_2.7.0_linux_arm64.tar.gz"
        sha256 "d07a996fe7adf0e309530bdca8dfe7c691ee777c2b20d19fda2e30e7c54a8495"

        def install
          bin.install "repos"
        end
      end
    end
  end
end
