# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repos < Formula
  desc "Cross-platform CLI for managing multiple related Git repositories as a unified workspace"
  homepage "https://github.com/MiguelRodo/repos"
  version "2.6.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/MiguelRodo/repos/releases/download/v2.6.0/repos_2.6.0_darwin_amd64.tar.gz"
      sha256 "2bafe7b197ac0bc4838b55c74a719d92de0783a1dfeee56df685a0ccc066efe0"

      def install
        bin.install "repos"
      end
    end
    on_arm do
      url "https://github.com/MiguelRodo/repos/releases/download/v2.6.0/repos_2.6.0_darwin_arm64.tar.gz"
      sha256 "584a5eb3ded5e06bc546ce081eb1330b30589f67221a2fe7c43511049d138286"

      def install
        bin.install "repos"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/repos/releases/download/v2.6.0/repos_2.6.0_linux_amd64.tar.gz"
        sha256 "ed3afc495d3dac7a07445bbc1cec34044105857865fd7dcad260aeb1377622f9"

        def install
          bin.install "repos"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/repos/releases/download/v2.6.0/repos_2.6.0_linux_arm64.tar.gz"
        sha256 "24c9161dc08828a6a65f5da0bdd9a8e214782c50b90d541f0c488145d3f14964"

        def install
          bin.install "repos"
        end
      end
    end
  end
end
