# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Setupmjr < Formula
  desc "Cross-platform setup utility"
  homepage "https://github.com/MiguelRodo/setupmjr"
  version "0.7.2"
  license "MIT"

  depends_on "MiguelRodo/homebrew-tap/repos"

  on_macos do
    on_intel do
      url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.7.2/setupmjr_0.7.2_darwin_amd64.tar.gz"
      sha256 "dbec96445a4f00cbed943a1bc3c1c67f9e5cb3160c198e86cad27ab53e598772"

      def install
        bin.install "setupmjr"
      end
    end
    on_arm do
      url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.7.2/setupmjr_0.7.2_darwin_arm64.tar.gz"
      sha256 "e39c5a95dd688ee68bcc7511afb55734d42ece7325d393c808b9c2760af266da"

      def install
        bin.install "setupmjr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.7.2/setupmjr_0.7.2_linux_amd64.tar.gz"
        sha256 "895ff38b94748ab2e7ce8174a6a961b8d92eaf0ca73bd88713c62f04ef2d24d4"

        def install
          bin.install "setupmjr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.7.2/setupmjr_0.7.2_linux_arm64.tar.gz"
        sha256 "a329e4d60650c34e74479f5a002d5ad733dec27c885ac4064ee590e9b84995ae"

        def install
          bin.install "setupmjr"
        end
      end
    end
  end
end
