# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Setupmjr < Formula
  desc "Cross-platform setup utility"
  homepage "https://github.com/MiguelRodo/setupmjr"
  version "0.6.1"
  license "MIT"

  depends_on "MiguelRodo/homebrew-tap/repos"

  on_macos do
    on_intel do
      url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.6.1/setupmjr_0.6.1_darwin_amd64.tar.gz"
      sha256 "d65dce6b5a41cd5e5563ea0e6af50ea9d6b886addbd682c1cfedc46af3ef6510"

      def install
        bin.install "setupmjr"
      end
    end
    on_arm do
      url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.6.1/setupmjr_0.6.1_darwin_arm64.tar.gz"
      sha256 "13e46dfacf2574cb32b9f3bf612b3cea3097e809a51ea104d2f211c05a7e7c0d"

      def install
        bin.install "setupmjr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.6.1/setupmjr_0.6.1_linux_amd64.tar.gz"
        sha256 "03a9d181e20597bde5429b311209ae3e566452abfddae7611ccfcdd8485fe43e"

        def install
          bin.install "setupmjr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.6.1/setupmjr_0.6.1_linux_arm64.tar.gz"
        sha256 "cdd2e3fd9a000a6cca0d43734e1040ce83d5c279040648ab5163401bda7d0a90"

        def install
          bin.install "setupmjr"
        end
      end
    end
  end
end
