# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Setupmjr < Formula
  desc "Cross-platform setup utility"
  homepage "https://github.com/MiguelRodo/setupmjr"
  version "0.6.4"
  license "MIT"

  depends_on "MiguelRodo/homebrew-tap/repos"

  on_macos do
    on_intel do
      url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.6.4/setupmjr_0.6.4_darwin_amd64.tar.gz"
      sha256 "785eee4e97f0bc82e25e846d3cc3427b4d21836477fa0f885b4eebd89f221656"

      def install
        bin.install "setupmjr"
      end
    end
    on_arm do
      url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.6.4/setupmjr_0.6.4_darwin_arm64.tar.gz"
      sha256 "90f4e54125c4455fc877ad705bdea6614ad2fbde19cf2caa44ef0014daaaea4c"

      def install
        bin.install "setupmjr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.6.4/setupmjr_0.6.4_linux_amd64.tar.gz"
        sha256 "aef0553307f90c53c17cbc4411991df8ae6cc1d596fef83824133b8775dbf983"

        def install
          bin.install "setupmjr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MiguelRodo/setupmjr/releases/download/v0.6.4/setupmjr_0.6.4_linux_arm64.tar.gz"
        sha256 "e2561d766d879becfa7df5dd578790e5a30918a85622730c05163ebbef37c690"

        def install
          bin.install "setupmjr"
        end
      end
    end
  end
end
